name: ansible-sign
description: GPG-sign Ansible project repositories with `ansible-sign`
author: Rick Elrod <relrod@redhat.com>
inputs:
  gpg-secret-key:
    description: The private/secret GPG key. This should be stored in a GitHub Secret.
    required: true
  gpg-passphrase:
    description: The passphrase for the secret key specified with `gpg-secret-key`, if any.
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install ansible-sign
      run: pip install ansible-sign

    - name: Import GPG secret key
      run: echo "${{ inputs.gpg-secret-key }}" | gpg --import --no-tty --batch

    - name: Sign the repository
      run: ansible-sign project gpg-sign .
      env:
        ANSIBLE_SIGN_GPG_PASSPHRASE: ${{ inputs.gpg-passphrase }}

    - name: Commit the result
      run: |
        git config --global user.name "ansible-sign GitHub Action"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git add .ansible-sign
        git commit -sm "ansible-sign: Update and sign checksum manifest"
        git push
